name: Test

on:
  push:
    branches:
      - master  # or 'main' depending on your default branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Eclipse Temurin distribution
          java-version: '21'
          cache: 'sbt'

      - name: Run tests
        run: sbt test

